### ISSUE TITLE
Uncaught TypeError: string.indexOf is not a function

### ISSUE THREAD

**Issue by rwa96** [31i73/atom-dbg#31]
[Enter steps to reproduce:]

1. Create a Custom debug configuration ".atom-dbg.cson"
2. Press F5 to open target selection
3. Type any character key (except space) while the text input box is active

**Atom**: 1.19.7 x64
**Electron**: 1.6.11
**OS**: linux 4.12.10-1-ARCH
**Thrown From**: [dbg](https://github.com/31i73/atom-dbg) package 1.6.2

### Stack Trace

Uncaught TypeError: string.indexOf is not a function

```
At /usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:881

TypeError: string.indexOf is not a function
    at Object.exports.score (/usr/lib/atom/node_modules/fuzzaldrin/lib/scorer.js:60:31)
    at Object.score (/usr/lib/atom/node_modules/fuzzaldrin/lib/fuzzaldrin.js:36:22)
    at SelectListView.fuzzyFilter (/packages/dbg/node_modules/atom-select-list/src/select-list-view.js:234:32)
    at SelectListView.computeItems (/packages/dbg/node_modules/atom-select-list/src/select-list-view.js:216:18)
    at SelectListView.didChangeQuery (/packages/dbg/node_modules/atom-select-list/src/select-list-view.js:206:10)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at /usr/lib/atom/src/text-editor.js:624:32
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at DisplayLayer.emitDidChangeSyncEvent (/usr/lib/atom/node_modules/text-buffer/lib/display-layer.js:818:18)
    at /usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:739:29
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:738:41)
    at TextBuffer.module.exports.TextBuffer.applyChange (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:721:12)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:655:19)
    at Selection.module.exports.Selection.insertText (/usr/lib/atom/src/selection.js:480:43)
    at /usr/lib/atom/src/text-editor.js:1199:29
    at /usr/lib/atom/src/text-editor.js:1238:28
    at TextBuffer.module.exports.TextBuffer.transact (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:876:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/lib/atom/src/text-editor.js:1671:26)
    at /usr/lib/atom/src/text-editor.js:1232:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/lib/atom/src/text-editor.js:2615:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/lib/atom/src/text-editor.js:2581:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/lib/atom/src/text-editor.js:1230:19)
    at TextEditor.module.exports.TextEditor.insertText (/usr/lib/atom/src/text-editor.js:1196:19)
    at TextEditorComponent.didTextInput (/usr/lib/atom/src/text-editor-component.js:1644:22)
```

### Commands

```
  3x -1:30.5.0 core:move-down (input.hidden-input)
     -1:28.3.0 editor:newline (input.hidden-input)
  5x -1:24.1.0 core:backspace (input.hidden-input)
     -1:14.7.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:13.4.0 editor:newline (input.hidden-input)
     -1:01.3.0 core:move-right (input.hidden-input)
     -1:00.5.0 editor:newline (input.hidden-input)
  3x -0:45.5.0 core:backspace (input.hidden-input)
     -0:33.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:30.4.0 editor:newline (input.hidden-input)
  4x -0:28.7.0 core:backspace (input.hidden-input)
     -0:27.4.0 intentions:highlight (input.hidden-input)
     -0:27.2.0 core:save (input.hidden-input)
     -0:21.7.0 dbg:pause-continue (input.hidden-input)
     -0:14.5.0 editor:consolidate-selections (input.hidden-input)
     -0:14.5.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
build-make 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
dbg 1.6.2 
dbg-gdb 1.7.7 
file-icons 2.1.11 
intentions 1.1.5 
language-arm 1.2.2 
language-bison 1.0.0 
language-bison-flex 0.3.1 
language-glsl 2.0.1 
language-ini 1.19.0 
language-latex 1.1.1 
latextools 0.8.5 
markdown-preview-enhanced 0.14.10 
output-panel 0.3.4 
pdf-view 0.59.0 
platformio-ide-terminal 2.6.0 
```

**Comment by ProPuke** [comment]
whoops, cheers!
