### ISSUE TITLE
Uncaught Error: watch ~/ssg/dscs/.atom-dbg.cson ENOSPC

### ISSUE THREAD

**Issue by wknapek** [31i73/atom-dbg#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [dbg](https://github.com/31i73/atom-dbg) package 1.6.2

### Stack Trace

Uncaught Error: watch /home/wknapek/ssg/dscs/.atom-dbg.cson ENOSPC

```
At events.js:160

Error: watch /home/wknapek/ssg/dscs/.atom-dbg.cson ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/dbg/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/dbg/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/dbg/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/packages/dbg/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at /packages/dbg/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
  2x -9:14.4.0 core:confirm (input.hidden-input)
     -8:55.4.0 core:backspace (input.hidden-input)
     -8:54.8.0 core:confirm (input.hidden-input)
     -7:35.3.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:54.1.0 dbg:toggle-stack-list (input.hidden-input)
     -5:23.3.0 project-find:show (atom-pane.pane.active)
     -5:13.6.0 core:paste (div.line)
  3x -4:30.1.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -3:31.2.0 grammar-selector:show (atom-text-editor.editor)
     -3:06.5.0 intentions:highlight (input.hidden-input)
  5x -3:06.3.0 autocomplete-plus:activate (input.hidden-input)
     -2:30.9.0 core:confirm (input.hidden-input)
     -1:19.3.0 intentions:highlight (input.hidden-input)
     -1:15.6.0 symbols-view:go-to-declaration (span.syntax--meta.syntax--block.syntax--cpp)
     -0:46.2.0 dbg:custom-debug (input.hidden-input)
```

### Non-Core Packages

```
atom-clang 1.0.14 
autocomplete-modules 1.8.0 
busy-signal 1.4.3 
cpp-generator 0.1.0 
cpp-refactor 2.2.3 
dbg 1.6.2 
dbg-gdb 1.7.7 
formatter-clangformat 1.0.1 
git-plus 7.10.0 
ide-clangd 0.1.2 
ide-cpp 0.0.2 
intentions 1.1.5 
language-cpp14 0.6.2 
linter 2.2.0 
linter-ui-default 1.6.10 
output-panel 0.3.4 
```

**Comment by ProPuke** [comment]
Thanks for the report!

Looks like these were likely caused by an OS problem: The maximum number of files were likely already being watched, so `dbg` couldn't monitor its config files for changes.

If this starts happening I can't fix it (it probably means some other program on the machine is currently gobbling them all up, or system limits need to be set higher), but I can display a more friendly error message instead of just failing with a stacktrace.

So if the config files are modified they won't automatically update if this happens, but it will now display a nicer error message explaining this instead of just dying.
