### ISSUE TITLE
Uncaught TypeError: Callback must be a function

### ISSUE THREAD

**Issue by ritikmittal** [31i73/atom-dbg#48]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [dbg](https://github.com/31i73/atom-dbg) package 1.6.3

### Stack Trace

Uncaught TypeError: Callback must be a function

```
At fs.js:138

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:138:9)
    at Object.writeFile (fs.js:1215:14)
    at ReadFileContext.callback (/packages/dbg/lib/ConfigManager.coffee:149:7)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:247:13)
```

### Commands

```
     -0:31.3.0 dbg:pause-continue (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-material-ui 2.1.3 
atom-typescript 13.7.0 
autocomplete-clang 0.13.1 
autocomplete-sql 0.5.0 
autosave-onchange 1.5.1 
busy-signal 2.0.1 
CPP-Competitive-Programming-Snippets 1.0.1 
cpp-syntax 0.0.0 
dbg 1.6.3 
dbg-gdb 1.7.8 
drunken-php 0.2.4 
emmet 2.4.3 
es6-javascript 1.0.0 
flask-snippets 0.3.3 
fold-functions 0.11.0 
gpp-compiler 3.0.7 
gtk-dark-theme 0.1.4 
Hydrogen 2.14.4 
ide-json 0.2.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-cpp14 0.6.2 
language-ejs 0.4.0 
language-kotlin 0.5.0 
language-lua-wow 0.2.0 
language-matlab 0.2.1 
linter 2.3.1 
linter-gcc 0.9.0 
linter-ui-default 1.8.1 
output-panel 0.3.4 
python-snippets 1.9.0 
react 0.18.0 
seti-icons 1.5.4 
Sublime-Style-Column-Selection 1.7.5 
terminal-tab 0.6.0 
xml-formatter 0.13.0 
```

**Comment by ell1e** [comment]
Got the same problem when clicking the "Save" button in the "Configure Custom Debug Session..." pane, and it doesn't seem to be saved at all (configuration is gone when I reopen Atom). So it'd be useful if this was addressed somehow
